### PR TITLE
Add commas to format specifiers

### LINKED ISSUE #1556: Format specifiers should be separated by commas
### Describe the bug
Format specifiers should be separated by commas. Intel raises errors if this is not the case

### To Reproduce
Provide code to reproduce the behaviour:
```python
print("multistrings", "one", "two with\ttab", "   three     ")
```

### Error details
The generated code is:
```fortran
write(stdout, '(A A A A A A A)', advance="yes") 'multistrings' , '&
      & ' , 'one' , ' ' , 'two with' // ACHAR(9) // 'tab' , ' ' , &
      &'   three     '
```
The intel compiler generates the error message:
```
2023-10-13T18:06:37.9618336Z /home/runner/work/pyccel/pyccel/tests/pyccel/scripts/__pyccel__gw0/prog_print_strings.f90(23): error #7421: A constant or general expression must appear in a format list in this context.   [AAAAAAA]
2023-10-13T18:06:37.9618875Z   write(stdout, '(A A A A A A A)', advance="yes") 'multistrings' , ' ' , &
2023-10-13T18:06:37.9619096Z ------------------^
```
https://github.com/pyccel/pyccel/actions/runs/6511414122/job/17687068773

### Expected behaviour
The generated code should be:
```fortran
write(stdout, '(A, A, A, A, A, A, A)', advance="yes") 'multistrings' , '&
      & ' , 'one' , ' ' , 'two with' // ACHAR(9) // 'tab' , ' ' , &
      &'   three     '
```

### Language
Fortran

### PR DESCRIPTION
**Pull request by EmilyBourne**
Add commas to format specifiers to fix #1556

### CODE REVIEW

**Comment by EmilyBourne** [comment]
I confirm that this fixes the issue with the intel compiler and reduces the number of errors seen in our tests (https://github.com/pyccel/pyccel/actions/runs/6532446936/job/17736379496)

The fixed tests are:
- `` test_multiple_results``
- `` test_print_strings``
- `` test_print_tuples``
- `` test_print_sp_and_end``
- `` test_c_arrays``
- `` test_return_numpy_arrays``
- `` test_array_binary_op``
- `` test_function``
- `` test_augassign_array_func``

**Review by yguclu — APPROVED** [review]
Looks good

**Pull request merged**
