### PR TITLE
Remove unnecessary set class (pyccel #2018)

### LINKED ISSUE #2018: Remove unnecessary set class
### Describe the bug
Currently Pyccel contains both `SetDiscard` describing the `discard` method and `SetRemove` describing the `remove` method.

The descriptions of these methods are:

```python
In [9]: a.discard?
Docstring:
Remove an element from a set if it is a member.

If the element is not a member, do nothing.
Type:      builtin_function_or_method

In [10]: a.remove?
Docstring:
Remove an element from a set; it must be a member.

If the element is not a member, raise a KeyError.
Type:      builtin_function_or_method

```

As Pyccel does not handle errors `SetDiscard` could be used to represent `SetRemove`. `SetRemove` does not require anything that is not already present in `SetDiscard`.

### PR DESCRIPTION
**Pull request by movassaghi6**
Remove the unnecessary class `SetRemove`. Fixes #2018

**Commit Summary**
- Delete `SetRemove` class from `ast/builtin_methods/set_methods.py`
- Replace `SetRemove` method with `SetDiscard` for `remove` keyword in `SetClass` methods in `ast/class_defs.py`

### CODE REVIEW

**Comment by EmilyBourne** [comment]
This looks good. It's nice that it works out of the box with no additional changes.
Looking at the checklist it seems that these 3 boxes are checked but have not been dealt with:
- Update Changelog
- Ensure any relevant issues are linked
- Update AUTHORS file

Is there a reason for that? I agree that the Changelog may not need to be modified here as `SetRemove` was a new class in this version anyway. However it is important to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue) so it is automatically closed when this PR is merged. I guess you didn't update the AUTHORS file as you only removed code? The bot will only remind you to add yourself to the AUTHORS on the first PR so we usually prefer to do this immediately so it isn't forgotten. Plus the AUTHORS file generally reflects the contributors and GitHub certainly thinks that cleaning code is a valid contribution.

**Comment by EmilyBourne** [comment]
> ok thank you . so update ChangeLog is not needed but I should link the issue and update authors file , right?

Yes exactly

**Review by EmilyBourne — APPROVED** [review]
This looks good. Thanks for cleaning up the code :smiley:

**Comment by movassaghi6** [comment]
Thank you Emily. wish to make bigger PRs in the future.

**Comment by EmilyBourne** [comment]
@movassaghi6 Sounds good to me. Always better to start small to get the lay of the land :smiley:

**Comment by movassaghi6** [comment]
@EmilyBourne thanks Emily . totally agree.

**Pull request merged**
