### PR TITLE
Remove Python 3.7 support

### LINKED ISSUE #1426: Python 3.7 End of Life
Python 3.7 reaches end of life today. We can now drop official support for 3.7 and update our CI workflows.

### PR DESCRIPTION
**Pull request by EmilyBourne**
This PR removes official support for Python 3.7. This fixes #1426. In order to merge this PR the required tests must be updated

### CODE REVIEW

**Review by sboof911 — APPROVED** [review]
Looks Good.

**Review by yguclu — APPROVED** [review]

**Comment by yguclu** [comment]
Should we not require Python 3.8 in our `setup.cfg`?

**Comment by EmilyBourne** [comment]
> Should we not require Python 3.8 in our `setup.cfg`?

I didn't realise that file specified the version. Fixed

**Pull request merged**
