### PR TITLE
Add python support for DICT get method

### PR DESCRIPTION
**Pull request by shoaib-moeen**
Add Python support for the dict get method. Fixes https://github.com/pyccel/pyccel/issues/1885

### CODE REVIEW

**Comment by EmilyBourne** [comment]
@shoaib-moeen I can't work out how to reopen this PR and point it at `devel`

**Review by jalalium — APPROVED** [review]
Very good job!

**Review by EmilyBourne — APPROVED** [review]
@shoaib-moeen Thanks for this pull request. This all looks good to me too.

**Pull request merged**
