### PR TITLE
Allow casting to bool within an if statement

### LINKED ISSUE #418: _visit_Is and _visit_IsNot in the semantic parser does not check if there is a bool() method in the expression
**Describe the bug**
_visit_Is and _visit_IsNot in the semantic parser does not check if there is a bool() method in the expression.

**To Reproduce**
For example this python code : 
```
def f():
    a = False
    x = 6
    if a is bool(x):
        x = x - 1
    return False
```

lead to this error : 
```
  File ".../pyccel/codegen/printing/fcode.py", line 1998, in _print_Is
    if a.dtype is NativeBool() and b.dtype is NativeBool():
AttributeError: 'bool' object has no attribute 'dtype'
```
after checking the expression that is passed to _print_Is function, i found it like that : 

`Is(a, bool(x))`

**Expected behavior**
the expression must be like that : 

`Is(a, Bool(x))`

**Language** 
In both C and Fortran

### PR DESCRIPTION
**Pull request by EmilyBourne**
Allow casting to bool within an if statement. Fixes #418 

- Ensure members of Is statement are visited.
- Ensure error messages clearly explain restrictions
- Create _handle_is_operator function to remove Is/IsNot duplication

### CODE REVIEW

**Comment by nhamidn** [comment]
i forgot to mention that the _visit_IsNot also contain by this error

**Comment by EmilyBourne** [comment]
> i forgot to mention that the _visit_IsNot also contain by this error

You are right the methods for the 2 functions are identical apart from the class name. I have created a function called by both of them to reduce duplication and stop problems existing in both being fixed only for one of the 2.

**Review by nhamidn — APPROVED** [review]

**Review by yguclu — COMMENTED** [review]
How should `is` and `is not` be used now?
The do not appear to be symmetric operators any more.

**Comment by EmilyBourne** [comment]
> How should is and is not be used now?
> The do not appear to be symmetric operators any more.

I'm not sure I understand your question.
The code is essentially the same as before. The are only 2 differences. 
1. Both sides are now visited instead of assuming that the lhs is a Variable and the rhs is a Variable, Boolean or None.
2. The 2 operators use the same code

Do you mean that you would like expressions such as:
```
a = True
True is a
```
to be acceptable?
The code above gives the following error in the master branch:
```
ERROR at annotation (semantic) stage
pyccel: [semantic] 
 |fatal: 3| Undefined variable (True)
```
and this error in this branch:
```
ERROR at annotation (semantic) stage
pyccel: [semantic] 
 |error: 3| Only variables are allowed as lhs for is statement
```

**Comment by yguclu** [comment]
> Do you mean that you would like expressions such as:
> 
> ```
> a = True
> True is a
> ```
> 
> to be acceptable?

Exactly, there is no reason to distinguish between left-hand side and right-hand side here.

I noticed that you added the error `PYCCEL_RESTRICTION_IS_LHS`, so I wrongly assumed that you had to add a restriction in order to get things working. I did not realize that the behavior in the master branch was also wrong.

**Review by yguclu — APPROVED** [review]

**Pull request merged**
