### PR TITLE
Reduce number of calls to get_attribute_nodes

### PR DESCRIPTION
**Pull request by EmilyBourne**
`get_attribute_nodes` is a bottleneck for `test_generic_functions.py` as can be seen here:
```
Thu Mar 18 11:10:41 2021    gen_master.txt

         22099009 function calls (21155989 primitive calls) in 118.964 seconds

   Ordered by: internal time
   List reduced from 7926 to 5 due to restriction <5>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      580   67.669    0.117   67.669    0.117 {method 'poll' of 'select.poll' objects}
      444   12.724    0.029   12.724    0.029 {method 'read' of '_io.BufferedReader' objects}
447133/23379    3.122    0.000    5.093    0.000 /home/emily/.local/lib/python3.6/site-packages/pyccel/ast/basic.py:120(get_attribute_nodes)
138795/136173    2.741    0.000    6.150    0.000 /home/emily/.local/lib/python3.6/site-packages/pyccel/ast/basic.py:34(__init__)
5852690/5852151    2.714    0.000    2.721    0.000 {built-in method builtins.isinstance}
```
This PR removes a call to `get_attribute_nodes` and narrows the search parameters of other calls.
It also avoids repeated unravelling by storing a boolean in a CodeBlock to indicate whether the code is stored in python vectorized syntax or not

```
Thu Mar 18 11:16:07 2021    gen_tweaks.txt

         22058694 function calls (21108203 primitive calls) in 116.041 seconds

   Ordered by: internal time
   List reduced from 7950 to 5 due to restriction <5>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      590   65.463    0.111   65.463    0.111 {method 'poll' of 'select.poll' objects}
      443   12.523    0.028   12.523    0.028 {method 'read' of '_io.BufferedReader' objects}
138795/136173    2.869    0.000    5.798    0.000 /home/emily/.local/lib/python3.6/site-packages/pyccel/ast/basic.py:34(__init__)
426378/22030    2.714    0.000    4.606    0.000 /home/emily/.local/lib/python3.6/site-packages/pyccel/ast/basic.py:121(get_attribute_nodes)
5815666/5815127    2.673    0.000    2.679    0.000 {built-in method builtins.isinstance}
```

### CODE REVIEW

**Review by mostafaMamoni — APPROVED** [review]

**Comment by yguclu** [comment]
@EmilyBourne Can you give us the profiling output for this branch?

**Comment by EmilyBourne** [comment]
@yguclu I have updated the description

**Comment by yguclu** [comment]
> @yguclu I have updated the description

Thanks!

The number of function calls was reduced from 447133 to 426378 from what I can see.

Are you after marginal gains, or do you think we could obtain major speedups in more complicated situations?

**Comment by EmilyBourne** [comment]
@yguclu In the tests this will give marginal gains. But I suspect it could have a bigger effect in more realistic functions with a large function body

**Review by yguclu — APPROVED** [review]

**Pull request merged**
