### PR TITLE
Fix installation instructions

### PR DESCRIPTION
**Pull request by mkaddani**
updating the Readme.md as mentioned in #1370 to fix Pip optional argument fails with zsh

### CODE REVIEW

**Comment by EmilyBourne** [comment]
@mkaddani I have cancelled your tests. They will be rerun when you press the "Ready for review" button (or ask the bot to mark as ready). As you haven't changed any code I don't see any reason to run these before deciding that the PR is ready

**Comment by mkaddani** [comment]
@EmilyBourne ah okey, i was following (exploring) the bot instructions.
Thank you!

**Comment by EmilyBourne** [comment]
> Yes, that makes sense. We should probably expand the bot description here : https://github.com/pyccel/pyccel/blob/master/ci_tools/bot_messages/bot_commands.txt so it says that these tests are run. Feel free to do that on this branch. It is also docs

I will fix this in #1381 . Please can you take a look and let me know if you think the messages are clearer

**Review by EniddeallA — APPROVED** [review]
Looks good!

**Review by EmilyBourne — APPROVED** [review]

**Pull request merged**
