### PR TITLE
Only run tests w/ Python 3.5 on Linux on non-master branches

### PR DESCRIPTION
**Pull request by yguclu**
This speeds up our builds on Travis-CI and solves #496

### CODE REVIEW

**Comment by yguclu** [comment]
This does not work as I expected. For a PR `branch` does not refer to the current branch name, but rather to the base branch name.

**Comment by EmilyBourne** [comment]
> This does not work as I expected. For a PR `branch` does not refer to the current branch name, but rather to the base branch name. This means that as soon as one creates a draft pull request, all builds are triggered.
> 
> @EmilyBourne @saidctb Any suggestion here?

https://stackoverflow.com/a/57519118/5957195 ?

**Comment by yguclu** [comment]
@EmilyBourne I thought we needed a [conditional build](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-builds), not a conditional stage (just below the other)

**Comment by yguclu** [comment]
I see now, this should be a [conditional job](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-jobs) instead :smile:

**Review by EmilyBourne — APPROVED** [review]

**Pull request merged**
