### PR TITLE
Correctly calculate the shape of slice 

### PR DESCRIPTION
**Pull request by MenoIy**
Correctly calculate the shape of a slice element when `start` and `stop` arguments are negative:

- Check slice's start and stop values and calculate the size using the base array shape;
- Convert step to positive if it's negative;
- Raise `ValueError` when the slice step is zero;
- Divide the result by the step and round it up if the step is not `None`.

### CODE REVIEW

**Review by saniQQ — APPROVED** [review]

**Comment by EmilyBourne** [comment]
Could you add a test please
Eg
```
a=b[1:]+b[:-1]
```

**Comment by MenoIy** [comment]
> Could you add a test please
> Eg
> 
> ```
> a=b[1:]+b[:-1]
> ```

@EmilyBourne  The new calculated shape is either PyccelSub,  PyccelAdd, or MathCeil to create a test I need issue #577, which will
translate Pyccel expressions to Sympy and then compare it.
@rmahjoubi

**Review by rmahjoubi — APPROVED** [review]

**Review by saniQQ — APPROVED** [review]

**Review by EmilyBourne — APPROVED** [review]

**Comment by yguclu** [comment]
Why does it say that "This Issue is blocked by *Allow simplification of pyccel-created nodes*"?

**Comment by EmilyBourne** [comment]
> Why does it say that "This Issue is blocked by _Allow simplification of pyccel-created nodes_"?

In order for the tests to work either issue #564 or #577 needed to be fixed. #577 simplifies the result with sympy which allows a comparison while #564 ensures that internal objects do not contain unnatural expressions which leads to the same result.

For example if we test the following:
`a[1:]+a[:-1]`
Before this PR the shapes were:
`PyccelMinus(Shape(a), 1)` and `PyccelUnary(1)`
After this PR the shapes are:
`PyccelMinus(Shape(a), 1)` and `PyccelAdd(Shape(a),PyccelUnary(1))`
#577 changes these to a sympy expression when checking if the shape is acceptable so it recognises that these are the same.
Alternatively #564 would mean that the shapes would have been simplified at creation to:
`PyccelMinus(Shape(a), 1)` and `PyccelMinus(Shape(a), 1)`

**Review by yguclu — APPROVED** [review]

**Pull request merged**
