### PR TITLE
Simd omp

### PR DESCRIPTION
**Pull request by nhamidn**
WIP

### CODE REVIEW

**Comment by EmilyBourne** [comment]
What is missing for this PR to be ready for review?

**Comment by nhamidn** [comment]
> What is missing for this PR to be ready for review?

i want to add the missing clause of the simd construct.

it seems that this branch is failing too

**Comment by yguclu** [comment]
Hi @nhamidn, this branch appears to be stale. Can you please give me a status update?

**Comment by nhamidn** [comment]
> Hi @nhamidn, this branch appears to be stale. Can you please give me a status update?

you are right @yguclu, i think we can close this PR, since there is another PR https://github.com/pyccel/pyccel/pull/1226 in progress where @Hellio404  is rewriting the whole OpenMP pragmas, however, he can come to it to check the text grammar used for the simd construct and it clauses if needed.

**Pull request closed without merging**
