### PR TITLE
Devel numpyext

### PR DESCRIPTION
**Pull request by yguclu**
This fixes issue #236 and (temporarily) #243

### CODE REVIEW

**Comment by EmilyBourne** [comment]
At least some of the errors are coming from the change in the default integer precision. It is changed for the arguments. But not for the dummy variables or any local variables. Their definition seems to be done at line 2070 of ast/core.py. But if I modify that to use the default_precision dictionary then the function call is a problem (see tests/pyccel/scripts/test_funcs.py for example code):
 ```
print *, sum_to_n(4)
        1
Error: Type mismatch in argument 'n' at (1); passed INTEGER(4) to INTEGER(8)
```
My impression is that fixing the problem in ast/core.py is enough. But there seem to be quite a lot of other places where the precision is set manually without checking the dictionary. The ones I found (for ints, but I think real/complex are mostly in the same place) are:
parser/syntax/headers.py: lines 62, 106,
parser/semantic.py: lines 646, 901, 963

I will push a commit with this fix, but it won't fix the problem for literal types. Something like this will need to be written instead:
`print *, sum_to_n(4_8)`

**Comment by yguclu** [comment]
> At least some of the errors are coming from the change in the default integer precision. It is changed for the arguments. But not for the dummy variables or any local variables. Their definition seems to be done at line 2070 of ast/core.py. But if I modify that to use the default_precision dictionary then the function call is a problem (see tests/pyccel/scripts/test_funcs.py for example code):
> 
> ```
> print *, sum_to_n(4)
>        1
> Error: Type mismatch in argument 'n' at (1); passed INTEGER(4) to INTEGER(8)
> ```
> 
> My impression is that fixing the problem in ast/core.py is enough. But there seem to be quite a lot of other places where the precision is set manually without checking the dictionary. The ones I found (for ints, but I think real/complex are mostly in the same place) are:
> parser/syntax/headers.py: lines 62, 106,
> parser/semantic.py: lines 646, 901, 963
> 
> I will push a commit with this fix, but it won't fix the problem for literal types. Something like this will need to be written instead:
> `print *, sum_to_n(4_8)`

@EmilyBourne Thanks for the bugfix. I am going to look into literal constants now.

**Comment by yguclu** [comment]
All unit tests are passing now.

**Comment by yguclu** [comment]
I am waiting for some feedback from @ratnania before merging this into master.

**Comment by yguclu** [comment]
@EmilyBourne You can use [`shutil`](https://docs.python.org/3/library/shutil.html#module-shutil) to remove the directories

**Pull request merged**
