### PR TITLE
Ensure master tests are triggered on cuda_main

### PR DESCRIPTION
**Pull request by EmilyBourne**
The `cuda_main` and `cuda_devel` branches should have the same tests as the master branch. These tests are activated here.

This PR also updates this branch to merge in changes from master

### CODE REVIEW

**Comment by EmilyBourne** [comment]
@yguclu I am going to need a hand merging this into cuda_devel and cuda_main. The branches are out of date and some of the things that need merging were sent to master before we made the coverage tests

**Comment by yguclu** [comment]
> @yguclu I am going to need a hand merging this into cuda_devel and cuda_main. The branches are out of date and some of the things that need merging were sent to master before we made the coverage tests

How can I help? Should we add come unit tests to this PR?

**Comment by EmilyBourne** [comment]
> > @yguclu I am going to need a hand merging this into cuda_devel and cuda_main. The branches are out of date and some of the things that need merging were sent to master before we made the coverage tests
> 
> How can I help? Should we add come unit tests to this PR?

If we want to add unit tests to fix the problem then we need to open issues and merge them to master. Otherwise I was thinking the simplest for now is just for an admin (ie you) to merge the first PR. The problem shouldn't arise again unless we have a similar problem after changing the CI further

**Comment by yguclu** [comment]
> > > @yguclu I am going to need a hand merging this into cuda_devel and cuda_main. The branches are out of date and some of the things that need merging were sent to master before we made the coverage tests
> > 
> > 
> > How can I help? Should we add some unit tests to this PR?
> 
> If we want to add unit tests to fix the problem then we need to open issues and merge them to master. Otherwise I was thinking the simplest for now is just for an admin (ie you) to merge the first PR. The problem shouldn't arise again unless we have a similar problem after changing the CI further

And by "first PR" you mean "this PR"?

**Comment by EmilyBourne** [comment]
> > > > @yguclu I am going to need a hand merging this into cuda_devel and cuda_main. The branches are out of date and some of the things that need merging were sent to master before we made the coverage tests
> > > 
> > > 
> > > How can I help? Should we add some unit tests to this PR?
> > 
> > 
> > If we want to add unit tests to fix the problem then we need to open issues and merge them to master. Otherwise I was thinking the simplest for now is just for an admin (ie you) to merge the first PR. The problem shouldn't arise again unless we have a similar problem after changing the CI further
> 
> And by "first PR" you mean "this PR"?

This PR for `cuda_main`, followed by a PR doing `cuda_main`->`cuda_devel` as the first PR for `cuda_devel`

**Pull request merged**
