### PR TITLE
Remove mpi4py dependency

### LINKED ISSUE #255: Make mpi4py requirement optional?
Since not everyone intends to use MPI, it would be nice to have mpi4py requirement optional. This would also allow for easier use on Windows (see #194) without requiring a compiler and and installing MSMPI. Related to #251 .

### PR DESCRIPTION
**Pull request by yguclu**
closes #255

### CODE REVIEW

**Comment by EmilyBourne** [comment]
If we remove dependencies that are only relevant for the tests should we not also remove pytest?

**Comment by krystophny** [comment]
pytest should also be removed as a dependency in my opinion, as it’s not needed to run pyccel

**Comment by yguclu** [comment]
Yes, we could remove `pytest` from our dependencies. But in general I would like the user to always run the tests on his/her machine after installing the library, so I was a little reluctant to remove pytest.

**Comment by yguclu** [comment]
So I have also removed `pytest` from our dependencies and updated the README file. I will proceed with merging.

**Pull request merged**
