### PR TITLE
Added Python Support for Lists

### PR DESCRIPTION
**Pull request by n-keerthi-gayathri**

### CODE REVIEW

**Comment by EmilyBourne** [comment]
Hey @n-keerthi-gayathri ,

Thank you very much for diving into the project and submitting your pull request! It's great to see new contributors like you getting involved in the project.

That said there seems to have been an unfortunate lack of communication about this. The issue that you tackle here is already assigned to @Farouk-Echaref and @mustapha-belbiad . I would strongly recommend that you ensure you can be assigned to an issue before starting to tackle it (by discussing on the issue) to prevent duplication of efforts.

As part of their work they have started by breaking down #1529 into 13 sub-issues (# 1689 - 1701). As this PR is not yet complete anyway (e.g tests, documentation still needed), would you mind picking one of the unassigned sub-issues to work on? This way, your code won't go to waste, and we can ensure a more coordinated approach to resolving the issue.

**Comment by n-keerthi-gayathri** [comment]
@EmilyBourne thank you for your encouragement and please assign me the sub-issues

**Comment by EmilyBourne** [comment]
> @EmilyBourne thank you for your encouragement and please assign me the sub-issues

@n-keerthi-gayathri Just let me know which sub-issue you want to tackle first. #1689 and #1690 have already been taken but the others are still available

**Comment by EmilyBourne** [comment]
> @EmilyBourne If possible, assign both #1701 and #1699 or either of them Thank You

I agree that #1699 and #1701 are similar enough to go in the same PR. Please leave a comment on the issues. For some reason GitHub won't let me assign someone unless they're either in the pyccel organisation or have commented on the issue I want to assign them to

**Comment by EmilyBourne** [comment]
@n-keerthi-gayathri You seem to have deleted your fork. Do you want me to un-assign you from #1701 and #1699 ?

**Comment by n-keerthi-gayathri** [comment]
No,Sorry I will fork again

**Pull request closed without merging**
