### PR TITLE
Improve bot functions

### PR DESCRIPTION
**Pull request by EmilyBourne**
Make some minor improvements to the bot:
- Allow bot to check checklist, description etc before bailing due to lack of trust.
- Allow running when user trust is indicated with @.
- Add @jalalium to trust givers
- Ensure pyccel/pyccel is available as a remote when running coverage on a fork

### CODE REVIEW

**Comment by EmilyBourne** [comment]
Beware, this branch is not tested on my fork

**Review by jalalium — APPROVED** [review]
Well done!

**Pull request closed without merging**
