### PR TITLE
Bot fixes

### PR DESCRIPTION
**Pull request by EmilyBourne**
Add new workflows to the bot to react to reviews and to run the tests on the `devel` branch. Fix a bug which stopped the bot from noticing when a PR was ready (Codacy not identified). Add a mechanism to avoid running tests if their dependencies haven't been changed. Ensure that all necessary tests work without a pull request (for tests on the `devel` branch).

### CODE REVIEW

**Comment by EmilyBourne** [comment]
Blocked by documentation bot issue. Solved in #1447

**Review by yguclu — APPROVED** [review]
All looks good to me, but we will know for sure only after merging! 😉 

Please update your fork with `devel`, so we can proceed.

**Pull request merged**
