### PR TITLE
Fix name collision issue for class methods

### LINKED ISSUE #1507: Method not correctly added in the ClassDef when functions has name collision.
### Describe the bug
The error comes from: https://github.com/pyccel/pyccel/blob/2fb0e0da37382e0ed8c144865547a70bcbb14b8c/pyccel/parser/semantic.py#L3576-L3576
This line should change to : `m = self.scope.functions.pop(cls.scope.get_expected_name(m_name))`.
And check if the method is correctly added to the `ClassDef.methods`.

### To Reproduce
Provide code to reproduce the behavior:
```python
class Point:
     def __init__(self):
         self.x = 1
         self.X = 1

    def get_x(self):
        return self.x

    def get_X(self):
        return self.X
```

### Error details
Provide the generated code, or the error message:
```bash/fortran/c
File "/home/pyccel/pyccel/parser/semantic.py", line 1633, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/pyccel/pyccel/parser/semantic.py", line 3576, in _visit_ClassDef
    m = self.scope.functions.pop(m_name)
```

### Expected behavior
The Code should work and the methods should be correctly added to the `ClassDef.methods`.

### PR DESCRIPTION
**Pull request by EmilyBourne**
Fix the name collision issue for class methods by using `Scope.get_expected_name` in `ClassDef.get_method` to get the name which should be used for searching. Ensure renamed functions are also added to classes. Add a test. Fixes #1507

### CODE REVIEW

**Comment by yguclu** [comment]
@EmilyBourne Please resolve the conflict in the semantic parser.

**Comment by EmilyBourne** [comment]
@yguclu Fixed

**Review by yguclu — APPROVED** [review]
Looks good to me!

**Pull request merged**
