### PR TITLE
Add support for multi operator expressions

### LINKED ISSUE #2081: Add support for multi operator expressions
### Describe the feature
Multi operator expressions can be useful. It would be nice to have support for this.

### Test Code
Provide code which does not currently work but which should do when this issue is fixed:
```python
if a <= x <= b:
    pass
```

### Proposed Solution
And and operator should be automatically inserted so `a <= x <= b` is understood as `a <= x and x <= b`

### Additional context
Needed by PyGyro

### PR DESCRIPTION
**Pull request by EmilyBourne**
Add support for multi operator expressions by extending the syntactic stage. Fixes #2081

### CODE REVIEW

**Review by jalalium — COMMENTED** [review]
I think it would be best to fix #2088 first to adequately test this PR. What do you think?

**Comment by EmilyBourne** [comment]
> I think it would be best to fix #2088 first to adequately test this PR. What do you think?

I don't think it should make a difference. This PR combines comparison operators which always return booleans. So I don't think #2088 is relevant.

This PR is also one of the necessary steps for PyGyro so I would like to keep putting those through if there's no urgence for #2088

**Review by jalalium — APPROVED** [review]
Well done!

**Pull request merged**
