### PR TITLE
Add support for @property

### LINKED ISSUE #1834: Add tests for `@property` decorator
### Describe the feature
The `@property` decorator is a very useful tool in classes. So much so that internally we have been using the property decorator without having added support for it in our translations. As a result it seems that this decorator now works out of the box! Currently a warning is raised claiming that we are ignoring the decorator:
```
pyccel:
 |warning [semantic]: tmp_cls.py| Decorator(s) not used (property)
```
However the code translates perfectly and clearly uses this property. We should therefore remove this warning, add tests and improve the documentation to show that this is supported.

### Test Code
The following code:
```python
class A:
    def __init__(self, x : float):
        self._x = x

    @property
    def x(self):
        return self._x

if __name__ == '__main__':
    x = 2.0
    y = A(x)
    z = y.x
```
currently raises the above warning but generates the following code:
```fortran
module tmp_cls


  use, intrinsic :: ISO_C_Binding, only : i64 => C_INT64_T , b1 => &
        C_BOOL , f64 => C_DOUBLE
  implicit none

  type, public :: A
    real(f64) :: private_x
    logical(b1), private :: is_freed

    contains
    procedure :: create => a_create
    procedure :: x => a_x
    procedure :: free => a_free
  end type A

  contains


  !........................................

  subroutine a_create(self, x)

    implicit none

    class(A), intent(inout) :: self
    real(f64), value :: x

    self%is_freed = .False._b1
    self%private_x = x

  end subroutine a_create

  !........................................


  !........................................

  function a_x(self) result(Out_0001)

    implicit none

    real(f64) :: Out_0001
    class(A), intent(inout) :: self

    Out_0001 = self%private_x
    return

  end function a_x

  !........................................


  !........................................

  subroutine a_free(self)

    implicit none

    class(A), intent(inout) :: self

    if (.not. self%is_freed) then
      ! pass
      self%is_freed = .True._b1
    end if

  end subroutine a_free

  !........................................


end module tmp_cls
```
```fortran
program prog_prog_tmp_cls

  use tmp_cls

  use, intrinsic :: ISO_C_Binding, only : i64 => C_INT64_T , b1 => &
        C_BOOL , f64 => C_DOUBLE
  implicit none

  real(f64) :: x
  type(A) :: y
  real(f64) :: z

  x = 2.0_f64
  call y % create(x)
  z = y % x()
  call y % free()

end program prog_prog_tmp_cls
```

Similarly for C:
```c
#include "tmp_cls.h"
#include <stdlib.h>
#include <stdbool.h>


/*........................................*/
void A__init__(struct A* self, double x)
{
    self->is_freed = 0;
    self->private_x = x;
}
/*........................................*/
/*........................................*/
double A__x(struct A* self)
{
    return self->private_x;
}
/*........................................*/
/*........................................*/
void A__del__(struct A* self)
{
    if (!self->is_freed)
    {
        // pass
        self->is_freed = 1;
    }
}
/*........................................*/
```
```c
#include "tmp_cls.h"
#include <stdlib.h>
#include <stdbool.h>
int main()
{
    double x;
    struct A y;
    double z;
    x = 2.0;
    A__init__(&y, x);
    z = A__x(&y);
    A__del__(&y);
    return 0;
}
```

### PR DESCRIPTION
**Pull request by EmilyBourne**
The semantic handling and the printing of methods using the `@property` decorator was already working, however official support for the decorator was missing due to the missing wrapper support. This PR adds the wrapping and removes the warning about this decorator. Fixes #1834 

**Commit Summary**
- Add documentation
- Prefer assertions for errors that only affect developers
- Allow the setter of a property to be missing (it is then saved as `None`)
- Add wrapping of a class property. The arguments of such functions are slightly different to those of a basic function.
- Add `-Wno-incompatible-pointer-types` to Python flags to remove unavoidable warnings
- Add tests

### CODE REVIEW

**Review by jalalium — COMMENTED** [review]
Awesome job! only a small remark that is probably beyond the scope of this PR.

```Python

class A:
    def __init__(self, x : int , y : int):
        self._x = x
        self._y = y
    
    @property
    def sum(self):
        return self.x + self._y

    @property
    def x(self):
        return self._x
```

This works fine in python but gives this error in pyccel:
```bash

ERROR at annotation (semantic) stage
pyccel:
 |fatal [semantic]: boo.py| Can't find method x in class A (<pyccel.ast.core.ClassDef object at 0x7cff407cbd00>)
```
It works just fine with functions:
```python
def g():
    return f() + h()

def f():
    return 3

def h():
    return 2
```

**Comment by EmilyBourne** [comment]
> Awesome job! only a small remark that is probably beyond the scope of this PR.

Yes. This is issue #2085 . It will be fixed and tested in #2087

**Comment by EmilyBourne** [comment]
> It works just fine with functions:

But not with functions in classes:
```python
class A:
    def g(self):
        return self.f() + self.h()

    def f(self):
        return 3

    def h(self):
        return 2
```

**Review by jalalium — APPROVED** [review]
Well done!

**Pull request merged**
