### PR TITLE
[cuda] device decorator

### PR DESCRIPTION
**Pull request by ohachim**

### CODE REVIEW

**Comment by bauom** [comment]
@ohachim what is the state of this PR?

**Comment by ohachim** [comment]
@bauom it needs tests to be set up

**Comment by ohachim** [comment]
@bauom, am not sure if that's how we are supposed to add the tests, I added a basic test to `tests/internal/scripts/ccuda/`, but it does not test errors and such.

**Comment by bauom** [comment]
In order to merge this pull request, it will be necessary to update the branch with the `cuda_main_temp` changes and add a simple test to check for any errors that may have been introduced. Additionally, the test should include a wrapper function for the `kernel`, as the current code does not allow for the automatic creation of such a function.
Please let me know if you have any questions or need further clarification.

**Comment by EmilyBourne** [comment]
What is the status of this PR? Please update the branch

**Comment by EmilyBourne** [comment]
@ohachim Please could you migrate this PR to the `pyccel/pyccel-cuda` repo. You can transfer your branch to that repo using the following commands:
```
git remote add cuda git@github.com:pyccel/pyccel-cuda.git
git checkout GPU_ddocs
git push -u cuda GPU_ddocs
```
cc: @bauom

**Comment by bauom** [comment]
This PR has being fixed in the current version.
and as it doesn't include a lot of code there is no need to copy it to the other Repo.

**Pull request closed without merging**
