### PR TITLE
[SET] Add c support for `clear`

### LINKED ISSUE #1918: [SETS] Add C support for `clear()`
### Test Code
Provide code which does not currently work but which should do when this issue is fixed:
```python
def foo():
    a = {1,2,1}
    a.clear()
```

### Proposed Solution
This feature should be implemented using the functionalities provided by STC

### PR DESCRIPTION
**Pull request by mustapha-belbiad**
Add C and Fortran support for the `set` method `clear`. Fixes #1918

### CODE REVIEW

**Comment by EmilyBourne** [comment]
@mustapha-belbiad this issue is finally unblocked! Do you plan on completing it or do you want me to pick it up?

**Review by jalalium — APPROVED** [review]
Well done!

**Pull request merged**
